spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework:
      security: debug
    org.hibernate: debug

server:
  port: 9191

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs